apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "climate-stack.fullname" . }}-config
  labels:
    {{- include "climate-stack.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
