apiVersion: v1
kind: Secret
metadata:
  name: {{ include "climate-stack.fullname" . }}-secrets
  labels:
    {{- include "climate-stack.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
